
services:
  db:
    image: postgres:16
    container_name: ems_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ems
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ems_net

  backend:
    container_name: ems_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ems
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"
    networks:
      - ems_net

  frontend:
    container_name: ems_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3001:3000"
    networks:
      - ems_net

  caddy:
    image: caddy:latest
    container_name: ems_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - ems_net

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  ems_net:
    driver: bridge
