name: Build and Deploy with GHCR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: andremugabo
        password: ${{ secrets.PAT_TOKEN }}

    - name: Set lowercase owner
      id: vars
      run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

    - name: Build backend image
      run: |
        docker build -t ghcr.io/${{ steps.vars.outputs.owner_lc }}/backend:latest ./backend

    - name: Build frontend image
      run: |
        docker build -t ghcr.io/${{ steps.vars.outputs.owner_lc }}/frontend:latest ./frontend

    - name: Push backend image
      run: |
        docker push ghcr.io/${{ steps.vars.outputs.owner_lc }}/backend:latest

    - name: Push frontend image
      run: |
        docker push ghcr.io/${{ steps.vars.outputs.owner_lc }}/frontend:latest

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PAT_TOKEN }}
          cd /path/to/your/project
          docker-compose pull
          docker-compose up -d
